name: haskell-parser
version: 0.1.0.0
github: "samwoolerton/haskell-parser"
license: BSD3
author: "Sam Woolerton"
maintainer: "samuelwoolerton@gmail.com"
copyright: "2020 Sam Woolerton"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/haskell-parser#readme>

dependencies:
  - base >= 4.7 && < 5
  - megaparsec
  - text
  - split

default-extensions:
  - OverloadedStrings
  - RecordWildCards
  - NumericUnderscores
  - InstanceSigs
  - MultiParamTypeClasses
  - FlexibleInstances
  - FlexibleContexts
  - EmptyCase
  - LambdaCase
  - MultiWayIf
  - NamedFieldPuns
  - TupleSections
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - DerivingStrategies
  - GeneralizedNewtypeDeriving
  - StandaloneDeriving
  - BangPatterns
  - KindSignatures
  - TypeOperators
  - ScopedTypeVariables
  - TypeApplications

library:
  source-dirs: src

executables:
  haskell-parser-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wall
      - -Wincomplete-uni-patterns
      - -Wincomplete-record-updates
      - -Wpartial-fields
      - -Wmissing-home-modules
      - -Widentities
      - -Wredundant-constraints
      - -Wmissing-export-lists
    dependencies:
      - haskell-parser

tests:
  haskell-parser-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wall
      - -Wincomplete-uni-patterns
      - -Wincomplete-record-updates
      - -Wpartial-fields
      - -Wmissing-home-modules
      - -Widentities
      - -Wredundant-constraints
      - -Wmissing-export-lists
    dependencies:
      - haskell-parser
